### ISSUE TITLE
Incorrect days since last butthurt

### ISSUE THREAD

**Issue by Kalabasa** [torchapps/butthurt#12]
![869 Days since last butthurt](http://i.imgur.com/2PNVyE7.png)

Should be "1 Days". (Also "Days" should be "Day")

Screenshot taken 2:40 PM, 7 May.

**Comment by ghost** [comment]
@Kalabasa what browser and OS are you using?

**Comment by Kalabasa** [comment]
Browser: Firefox 37.0.2
OS: Debian 8 "Jessie"

**Comment by ghost** [comment]
https://github.com/torchapps/butthurt/commit/dbe0701b50fcf82f96df8640837e506fff1a6e61
https://github.com/torchapps/butthurt/commit/c46f38a684cdb7a371d6bd75373c1f26e154fb5f

**Comment by ghost** [comment]
this is effectively solved, just having some trouble getting webpack to update the bundle

**Comment by ghost** [comment]
fix'd, @Kalabasa please confirm

**Comment by Kalabasa** [comment]
Yes, it's fixed.
