### ISSUE TITLE
stuck in terrible country

### ISSUE THREAD

**Issue by cmarguel** [torchapps/butthurt#3]
steps to reproduce
1. be born here

desired result:
not be here

actual result:
still here

**Comment by ghost** [comment]
confirmed, can reproduce. marking as important.

**Comment by cmarguel** [comment]
I have a temporary fix in place and am trying to push it now. Should be up by first quarter next year but this fix will only last from 6 months to a year so we'll need to figure out a more permanent solution during that period.

**Comment by ghost** [comment]
can i reproduce this PLS GAD JESUS

**Comment by cmarguel** [comment]
Pushed fix to production. Problem appears to be resolved, although the fix resides in volatile memory so we may need to reopen this issue at a later date.
