### ISSUE TITLE
add about page / section / modal

### ISSUE THREAD

**Issue by ghost** [torchapps/butthurt#4]
content:

> Butthurt is a tribute to Filipino (over)sensitivities, nothing more.
> 
> If you'd like to suggest a new entry, click [here](https://docs.google.com/forms/d/1Cexh4k5-nfwX9RKmv7Dwd4DcGweXLh8Kn6iZXbob0hU/viewform) or drop us a [pull request](https://github.com/torchapps/butthurt)!
> 
> Made by [Torch](https://torchapps.github.io)

**Comment by livtanong** [comment]
Done. eda5445
